name: Harvest n8n templates
on:
  schedule: [{ cron: "23 22 * * *" }]   # runs daily
  workflow_dispatch: {}
concurrency:
  group: harvest
  cancel-in-progress: false
permissions:
  contents: write
  pull-requests: write
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  harvest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      - name: Run harvester
        run: |
          python scripts/harvest.py | tee harvest.log
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/sync-templates
          title: "Chore: sync n8n templates"
          commit-message: "chore: sync catalogue and ingested templates"
          body: "Automated harvest, normalisation and dedupe."
          labels: "automation, n8n"
      - name: Open diagnostic issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Harvest failed"
          content-filepath: harvest.log
          labels: "bug, automation"
